# Generated by Django 4.1 on 2022-09-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_quntatiy_ordereditem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='OrderItem',
        ),
    ]
